### ISSUE TITLE
Proxy_on:  command not found/ proxy_off : command not found

### ISSUE THREAD

**Issue by sirackerman** [wnlen/clash-for-linux#31]
When I run "sudo bash start.sh", I am supposed to run "proxy_on"  after but it says "command not found'. The same thing happen when i ran " bash shutdown.sh", after entering proxy_off, it said "command not found". The vpn is off but I could still access certain website like google that are normally blocked which means the vpn is not entirely off. How to fix this issue to ensure that the vpn start well and is well turned off? I 've restarted my computer several times but the issue  hasn't been fixed. Thanks for anyone who can help. 
![Screenshot from 2024-08-22 14-30-04](https://github.com/user-attachments/assets/f5293159-b2b5-4389-9f2a-398470d9f6d3)

**Comment by ultwcz** [comment]
Hi， @sirackerman do you run command `source /etc/profile.d/clash.sh`

**Comment by sirackerman** [comment]
> Hi， @sirackerman do you run command `source /etc/profile.d/clash.sh`

I just did it and it works now. 
Thanks for the help🙏🏽

**Comment by v-49** [comment]
root@ubuntu-NF5280M5:~/clash-for-linux-master# ./shutdown.sh 

服务关闭成功，请执行以下命令关闭系统代理：proxy_off

root@ubuntu-NF5280M5:~/clash-for-linux-master# $ proxy_off
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 27, in <module>
    from CommandNotFound.util import crash_guard
ModuleNotFoundError: No module named 'CommandNotFound'
root@ubuntu-NF5280M5:~/clash-for-linux-master# source /etc/profile.d/clash.sh
root@ubuntu-NF5280M5:~/clash-for-linux-master# $ proxy_off
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 27, in <module>
    from CommandNotFound.util import crash_guard
ModuleNotFoundError: No module named 'CommandNotFound'
root@ubuntu-NF5280M5:~/clash-for-linux-master# sudo apt update
sudo apt install command-not-found
命中:1 http://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy InRelease                                                                                                    
命中:2 https://mirrors.aliyun.com/docker-ce/linux/ubuntu jammy InRelease                                                                                             
获取:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]                                                                                           
命中:6 https://nvidia.github.io/libnvidia-container/stable/deb/amd64  InRelease     Why is it not working?@ultwcz
