### ISSUE TITLE
服务器经常自己关闭

### ISSUE THREAD

**Issue by Jz1028** [wnlen/clash-for-linux#32]
每次启动后，过一段时间在curl就访问不同；
只有proxy_on就可以了。
为啥经常自己关闭

**Comment by la02w** [comment]
只要启动后就是在后台运行到7890端口的。
proxy_on是配置http_proxy环境变量，手动输入就是当前临时启用。可以配置到.bashrc进入自动配置

**Comment by Jz1028** [comment]
所以用的时候，需要把用的软件代理到7890吗？
终端下不会自动代理对吗？

**Comment by la02w** [comment]
> 所以用的时候，需要把用的软件代理到7890吗？ 终端下不会自动代理对吗？

终端下就是要配置(http_proxy)环境变量，如果想一直启动可以配置到系统环境变量或者用户的.bashrc 直接在文件末尾输入另起一行 proxy_on

**Comment by Jz1028** [comment]
原来如此，感谢！！！
