### ISSUE TITLE
部署 clash-for-linux 后，网络流量被恶意使用

### ISSUE THREAD

**Issue by holys** [wnlen/clash-for-linux#37]
昨天因测试需要，在腾讯云服务器上部署了clash-for-linux， 半夜流量突然异常，因为我的公网 IP 是按流量付费（50MB）, 且余额不多，很快就欠费了。 当时我还没睡，发现后马上充值了腾讯云，早上醒来又欠费了，
结合腾讯云的流量访问情况和我所使用的代理服务提供的流量访问情况，高度吻合，所以怀疑是 clash-for-linux 提供的服务被恶意访问了

腾讯云流量监控：

![WX20241003-111924@2x](https://github.com/user-attachments/assets/6ab31e62-8c5c-44c0-b267-caef4d0f5c74)

代理服务流量使用情况：
![WX20241003-111938@2x](https://github.com/user-attachments/assets/517fbc18-7c21-43e3-be68-a61960ec20dc)

一方面 当然是我这边的问题，没有做好端口限制（当时只是临时测试，没想这么多），
另一方面，不知道这个客户端是不是被什么人盯上了，恶意去扫描端口蹭流量不确定是否有这种情况？

**Comment by arnoliudaxia** [comment]
- 7890端口特征太明显了
- 加上没有basicAuth认证之类的

**Comment by xia-huang-411303** [comment]
笑死，居然有跟我一样把7890端口不加密放公网上的傻卵怨种
