### ISSUE TITLE
Clash订阅地址不可访问！

### ISSUE THREAD

**Issue by DeramOfTheLater** [wnlen/clash-for-linux#4]
请问在.env中的clash_url输入了订阅地址后，运行start.sh文件，显示订阅地址不可访问，他是不能用windows上的订阅地址吗

**Comment by ball-47** [comment]
你好，我遇到相同的问题，想请教一下你是怎么解决的？

**Comment by DeramOfTheLater** [comment]
换了一个

**Comment by la02w** [comment]
有些机场地址就是国内访问不了。需要先开梯子或者手动配置数据文件
