### ISSUE TITLE
怎么切换线路？

### ISSUE THREAD

**Issue by 1768637871** [wnlen/clash-for-linux#6]
无法使用UI界面，求教怎么使用命令行进行线路切换

**Comment by shuozhu1** [comment]
> 同问，进入ui后处于登录界面

您好，请问解决了吗，我也想问下

**Comment by shuozhu1** [comment]
> 您好，请问解决了吗，我也想问下

**Comment by shuozhu1** [comment]
> 无法使用UI界面，求教怎么使用命令行进行线路切换

您好，请问解决了吗，我也想问下

**Comment by 1768637871** [comment]
使用vscode做端口转发，将服务器上的端口转发到本机，访问(http://localhost:9090/ui)可以调整
